#!/usr/bin/env python

from string import *
import control

class Point:
	def __init__ (self, x=0, y=0, z=None):
		self.x = x
		self.y = y
		self.z = z
		self.lineto_id = {}

	def __repr__ (self):
		return '( ' + `self.x` + ' ' + `self.y` + ' )'

	def plot (self, color='blue'):
		self.plot_id = control.plot_disc (self.x, self.y, color)
		return self.plot_id

	def hilight (self, color='green'):
		self.hi = control.plot_disc (self.x, self.y, color, 5)
		return self.hi
	
	def unhilight (self, id = None):
		if id == None: id = self.hi
		control.plot_delete (id)
	
	def lineto (self, p, color='red'):
		self.lineto_id[p] = control.plot_line (self.x, self.y, p.x, p.y, color)
		return self.lineto_id[p]
	
	def remove_lineto (self, p, id = None):
		if id == None: id = self.lineto_id[p]
		control.plot_delete (id)
	
